// Code generated by jtd-codegen for TypeScript v0.2.0

export interface Person {
  father: Individual;
  firstName: string;
  lastName: string;
  mother: Individual;
}

export interface Individual {
  firstName: string;
  lastName: string;
}
